# Generated by Django 2.1.4 on 2021-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
