# Generated by Django 2.1.4 on 2021-10-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='accounts.Practice'),
        ),
    ]
