# Generated by Django 2.1.4 on 2021-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='practices'),
        ),
    ]
