# Generated by Django 2.1.4 on 2021-10-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_practice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
